"""ORM model for the ``alerts`` table.

Alerts are generated by Layer 1 pattern detection (gap_urgent, gap_briefing,
inertia, deterioration).  They are delivered to the clinician alert inbox and
must be acknowledged.  All three timestamp columns after ``triggered_at`` are
nullable — they advance as the alert moves through the delivery lifecycle.
"""


from datetime import datetime

from sqlalchemy import DateTime, Numeric, SmallInteger, String, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class Alert(Base):
    """A clinical alert generated for a patient by the pattern engine."""

    __tablename__ = "alerts"

    alert_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    patient_id: Mapped[str] = mapped_column(String, nullable=False)
    alert_type: Mapped[str] = mapped_column(
        String, nullable=False
    )  # gap_urgent|gap_briefing|inertia|deterioration
    gap_days: Mapped[int | None] = mapped_column(SmallInteger, nullable=True)
    systolic_avg: Mapped[float | None] = mapped_column(Numeric(5, 1), nullable=True)
    triggered_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, server_default=func.now()
    )
    delivered_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    acknowledged_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
