'use client'

import { createContext, useCallback, useContext, useEffect, useRef, useState } from 'react'
import { usePathname } from 'next/navigation'
import { X, ChevronRight, ChevronLeft } from 'lucide-react'

// ── Step definitions ──────────────────────────────────────────────────────────

interface TourStep {
  target: string
  title: string
  body: string
  position?: 'top' | 'bottom' | 'left' | 'right'
  route?: 'dashboard' | 'patient'
}

const ALL_STEPS: TourStep[] = [
  // ── Dashboard — left to right, top to bottom ──
  { target: 'nav-patients',           route: 'dashboard', position: 'right',
    title: 'Patients',
    body: 'Your main patient list, sorted by Chronic Risk tier then Priority Score. Start here every morning before consultations.' },
  { target: 'nav-alerts',             route: 'dashboard', position: 'right',
    title: 'Alerts',
    body: 'Active clinical flags — monitoring gaps, therapeutic inertia, adherence concerns, and deterioration. Unacknowledged alerts appear here.' },
  { target: 'nav-shadow',             route: 'dashboard', position: 'right',
    title: 'Shadow Mode',
    body: 'Validation tool: replays past visits and shows what ARIA would have flagged versus the physician\'s recorded decision. Does not affect live data.' },
  { target: 'nav-admin',              route: 'dashboard', position: 'right',
    title: 'Admin',
    body: 'Trigger the briefing scheduler manually, manage demo data, and view system status. Use this to generate a briefing if one hasn\'t appeared yet for today.' },
  { target: 'topbar-search',          route: 'dashboard', position: 'bottom',
    title: 'Search',
    body: 'Search patients by ID, name, or condition. Useful when you have a specific patient in mind rather than working through the full list.' },
  { target: 'topbar-bell',            route: 'dashboard', position: 'bottom',
    title: 'Alert Bell',
    body: 'Quick access to all unacknowledged alerts across all patients. Click to go directly to the Alerts page.' },
  { target: 'topbar-theme',           route: 'dashboard', position: 'bottom',
    title: 'Light / Dark Mode',
    body: 'Toggle between light and dark display. ARIA is designed for clinical use in both environments.' },
  { target: 'patient-chronic-risk',   route: 'dashboard', position: 'bottom',
    title: 'Chronic Risk',
    body: 'Set by diagnosis — CHF, Stroke, or TIA permanently sets High regardless of current readings. This is a lifetime cardiovascular risk classification, not today\'s urgency.' },
  { target: 'patient-chief-concern',  route: 'dashboard', position: 'bottom',
    title: 'Chief Concern',
    body: 'The primary clinical conditions driving this patient\'s risk — derived from their EHR problem list and diagnosis overrides.' },
  { target: 'patient-priority-score', route: 'dashboard', position: 'bottom',
    title: 'Priority Score',
    body: 'Today\'s urgency (0–100). Weighted: BP vs baseline (30%), days since last med change (25%), adherence (20%), monitoring gap (15%), comorbidities (10%). High Risk patients can score low if currently stable.' },
  { target: 'patient-bp-trend',       route: 'dashboard', position: 'bottom',
    title: 'BP Trend',
    body: 'Categorised relative to this patient\'s personal baseline from clinic history. High means above their own typical range — not a fixed population threshold.' },
  { target: 'patient-appointment',    route: 'dashboard', position: 'bottom',
    title: 'Appointment',
    body: 'Shows today\'s appointment time if the patient has a consultation scheduled today. Only today\'s appointments are highlighted — future dates show a dash.' },

  // ── Patient page — top to bottom document order ──
  { target: 'briefing-header',        route: 'patient', position: 'bottom',
    title: 'Pre-Visit Briefing Header',
    body: 'Shows the patient\'s Chronic Risk tier, Priority Score, appointment time, and when the briefing was generated and last read.' },
  { target: 'briefing-ai-summary',    route: 'patient', position: 'bottom',
    title: 'AI Summary',
    body: 'A plain-language summary generated by ARIA\'s Layer 3 LLM. It synthesises BP trend, medication status, and adherence signal into a single pre-read for the clinician.' },
  { target: 'briefing-bp-trend',      route: 'patient', position: 'bottom',
    title: 'BP Trend Chart',
    body: 'Home readings split into Morning and Evening sessions. The bold line is the daily average. Amber zone is 130–140 mmHg, red zone is above 140 mmHg.' },
  { target: 'briefing-medication',    route: 'patient', position: 'bottom',
    title: 'Medication Status',
    body: 'Current antihypertensive regimen from the EHR, including when each drug was last changed. Titration windows are flagged if a recent change is still within its expected adjustment period.' },
  { target: 'briefing-adherence',     route: 'patient', position: 'bottom',
    title: 'Adherence Signal',
    body: 'Per-medication dose confirmation rates. Green ≥80%, amber 60–80%, red below 60%. Used alongside BP to classify Pattern A (adherence concern) or B (treatment review).' },
  { target: 'briefing-problems',      route: 'patient', position: 'bottom',
    title: 'Active Problems',
    body: 'Active conditions from the patient\'s EHR problem list. These are factual context — not alerts. They inform how you interpret BP and adherence patterns during the consultation.' },
  { target: 'briefing-overdue-labs',  route: 'patient', position: 'bottom',
    title: 'Overdue Investigations',
    body: 'Lab tests and investigations that are pending or overdue based on the EHR. Flagged in red because they may be clinically relevant before or during today\'s visit.' },
  { target: 'briefing-agenda',        route: 'patient', position: 'bottom',
    title: 'Visit Agenda',
    body: 'Priority-ordered items for the consultation: urgent alerts first, then inertia, adherence concerns, overdue labs, and active problems.' },
  { target: 'chat-panel',             route: 'patient', position: 'left',
    title: 'Ask ARIA',
    body: 'Ask clinical questions in plain language — "Why was this patient flagged?", "What changed in the last 14 days?", "Which medication had the most missed doses?" ARIA answers from real patient data only.' },
]

// ── Context ───────────────────────────────────────────────────────────────────

interface TourContextValue { active: boolean; start: () => void }
const TourContext = createContext<TourContextValue>({ active: false, start: () => {} })
export function useTour() { return useContext(TourContext) }

// ── Smart positioning ─────────────────────────────────────────────────────────
// Viewport-space only — never add scrollY. Auto-flips to whichever side has room.

const POP_W = 300
const POP_H = 190
const GAP   = 12
const PAD   = 10

function smartPos(rect: DOMRect, preferred: TourStep['position'] = 'bottom') {
  const vw = window.innerWidth
  const vh = window.innerHeight

  // Available space on each side
  const space = {
    bottom: vh - rect.bottom,
    top:    rect.top,
    right:  vw - rect.right,
    left:   rect.left,
  }

  // Use preferred side if it fits, otherwise pick the side with most room
  const fits = {
    bottom: space.bottom >= POP_H + GAP,
    top:    space.top    >= POP_H + GAP,
    right:  space.right  >= POP_W + GAP,
    left:   space.left   >= POP_W + GAP,
  }

  let side = preferred ?? 'bottom'
  if (!fits[side]) {
    // Find side with most space
    side = (Object.entries(space).sort(([, a], [, b]) => b - a)[0][0]) as typeof side
  }

  let top = 0
  let left = 0

  switch (side) {
    case 'bottom':
      top  = rect.bottom + GAP
      left = rect.left + rect.width / 2 - POP_W / 2
      break
    case 'top':
      top  = rect.top - POP_H - GAP
      left = rect.left + rect.width / 2 - POP_W / 2
      break
    case 'right':
      top  = rect.top + rect.height / 2 - POP_H / 2
      left = rect.right + GAP
      break
    case 'left':
      top  = rect.top + rect.height / 2 - POP_H / 2
      left = rect.left - POP_W - GAP
      break
  }

  // Clamp within viewport
  top  = Math.max(PAD, Math.min(top,  vh - POP_H - PAD))
  left = Math.max(PAD, Math.min(left, vw - POP_W - PAD))

  return { top, left }
}

// ── Tour overlay ──────────────────────────────────────────────────────────────

function TourOverlay({ steps, onEnd }: { steps: TourStep[]; onEnd: () => void }) {
  const [stepIdx, setStepIdx]       = useState(0)
  const [targetRect, setTargetRect] = useState<DOMRect | null>(null)
  const timerRef                    = useRef<ReturnType<typeof setTimeout> | null>(null)

  const step    = steps[stepIdx]
  const isFirst = stepIdx === 0
  const isLast  = stepIdx === steps.length - 1

  const measureAfterScroll = useCallback((el: Element) => {
    // Scroll to center so element is fully visible before measuring
    el.scrollIntoView({ behavior: 'smooth', block: 'center' })

    if (timerRef.current) clearTimeout(timerRef.current)

    // Poll until position is stable (scroll animation finished)
    let lastY = -999
    let stableCount = 0
    const poll = () => {
      const r = el.getBoundingClientRect()
      if (Math.abs(r.top - lastY) < 0.5) {
        stableCount++
        if (stableCount >= 3) { setTargetRect(r); return }
      } else {
        stableCount = 0
      }
      lastY = r.top
      timerRef.current = setTimeout(poll, 60)
    }
    timerRef.current = setTimeout(poll, 60)
  }, [])

  useEffect(() => {
    setTargetRect(null) // clear while scrolling to avoid stale highlight
    const el = document.querySelector(`[data-tour="${step.target}"]`)
    if (el) measureAfterScroll(el)
    return () => { if (timerRef.current) clearTimeout(timerRef.current) }
  }, [step.target, measureAfterScroll])

  useEffect(() => {
    const onResize = () => {
      const el = document.querySelector(`[data-tour="${step.target}"]`)
      if (el) setTargetRect(el.getBoundingClientRect())
    }
    window.addEventListener('resize', onResize)
    return () => window.removeEventListener('resize', onResize)
  }, [step.target])

  const pos = targetRect ? smartPos(targetRect, step.position) : null

  return (
    <>
      {/* Backdrop */}
      <div className="fixed inset-0 z-40 bg-black/50" onClick={onEnd} />

      {/* Highlight ring around target */}
      {targetRect && (
        <div
          className="fixed z-40 rounded-lg pointer-events-none"
          style={{
            top:    targetRect.top    - 5,
            left:   targetRect.left   - 5,
            width:  targetRect.width  + 10,
            height: targetRect.height + 10,
            boxShadow: '0 0 0 9999px rgba(0,0,0,0.50), 0 0 0 3px rgba(59,130,246,0.6)',
          }}
        />
      )}

      {/* Popover — only renders after position is known */}
      {pos && (
        <div
          className="fixed z-50 bg-white dark:bg-[#1a2235]
                     rounded-xl shadow-2xl border border-gray-100 dark:border-[#2a3548] overflow-hidden"
          style={{ width: POP_W, top: pos.top, left: pos.left }}
          onClick={(e) => e.stopPropagation()}
        >
          {/* Progress */}
          <div className="h-0.5 bg-gray-100 dark:bg-[#2a3548]">
            <div
              className="h-full bg-blue-600 transition-all duration-300"
              style={{ width: `${((stepIdx + 1) / steps.length) * 100}%` }}
            />
          </div>

          <div className="px-4 pt-4 pb-3">
            <div className="flex items-start justify-between gap-2 mb-2">
              <div>
                <p className="text-[10px] font-semibold uppercase tracking-widest text-blue-500 dark:text-blue-400 mb-0.5">
                  {stepIdx + 1} / {steps.length}
                </p>
                <h3 className="text-[14px] font-semibold text-gray-900 dark:text-gray-100">
                  {step.title}
                </h3>
              </div>
              <button
                onClick={onEnd}
                className="w-6 h-6 flex items-center justify-center rounded
                           text-gray-400 hover:text-gray-600 dark:hover:text-gray-200
                           hover:bg-gray-100 dark:hover:bg-[#2a3548] flex-shrink-0"
              >
                <X size={13} strokeWidth={2} />
              </button>
            </div>
            <p className="text-[13px] text-gray-600 dark:text-gray-300 leading-relaxed">
              {step.body}
            </p>
          </div>

          <div className="flex items-center justify-between px-4 py-3
                          border-t border-gray-100 dark:border-[#2a3548]">
            <button
              onClick={() => setStepIdx((i) => i - 1)}
              disabled={isFirst}
              className="inline-flex items-center gap-1 text-[12px] font-medium
                         text-gray-400 hover:text-gray-700 dark:hover:text-gray-200
                         disabled:opacity-0 transition-colors"
            >
              <ChevronLeft size={13} strokeWidth={2} /> Back
            </button>

            <div className="flex items-center gap-1">
              {steps.map((_, i) => (
                <button
                  key={i}
                  onClick={() => setStepIdx(i)}
                  className={`rounded-full transition-all duration-200 ${
                    i === stepIdx
                      ? 'w-3 h-1.5 bg-blue-600'
                      : 'w-1.5 h-1.5 bg-gray-200 dark:bg-gray-600 hover:bg-gray-300'
                  }`}
                />
              ))}
            </div>

            {isLast ? (
              <button
                onClick={onEnd}
                className="text-[12px] font-semibold text-blue-600 dark:text-blue-400
                           hover:text-blue-700 transition-colors"
              >
                Done
              </button>
            ) : (
              <button
                onClick={() => setStepIdx((i) => i + 1)}
                className="inline-flex items-center gap-1 text-[12px] font-semibold
                           text-blue-600 dark:text-blue-400 hover:text-blue-700 transition-colors"
              >
                Next <ChevronRight size={13} strokeWidth={2} />
              </button>
            )}
          </div>
        </div>
      )}
    </>
  )
}

// ── Provider ──────────────────────────────────────────────────────────────────

export function TourProvider({ children }: { children: React.ReactNode }) {
  const [active, setActive] = useState(false)
  const pathname = usePathname()

  const isPatientPage = pathname.startsWith('/patients/') && pathname !== '/patients/'
  const steps = ALL_STEPS.filter((s) =>
    !s.route || s.route === (isPatientPage ? 'patient' : 'dashboard')
  )

  const start = useCallback(() => setActive(true),  [])
  const end   = useCallback(() => setActive(false), [])

  return (
    <TourContext.Provider value={{ active, start }}>
      {children}
      {active && <TourOverlay steps={steps} onEnd={end} />}
    </TourContext.Provider>
  )
}
